name: Java CI-CD Pipeline

# This tells GitHub to run the pipeline
# every time you push code to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # Use a free virtual machine hosted by GitHub
    runs-on: ubuntu-latest

    steps:
    # 1. Check out your code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Set up the correct Java version (JDK 25)
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'

    # 3. This is the "code build" step
    - name: Build Java app with Maven
      run: mvn package -DskipTests

    # 4. Set up Docker Buildx (for building images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 5. This is the "Docker build" step
    - name: Build the Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false # We are only building, not pushing to a registry
        tags: my-java-app:latest
